@startuml

package cli {
}

package enricher {
}

package filter {
}

package model {
}

package parser {
}

package project {
}

package renderer {
}

package "error" {
enum "ArchError" as error__ArchError
}

package "external" {
class File
class Visit
}

package "pipeline" {
class "Pipeline" as pipeline__Pipeline
class "PipelineBuilder" as pipeline__PipelineBuilder
}


pipeline__Pipeline --> parser : contains
pipeline__Pipeline --> enricher : contains
pipeline__Pipeline --> filter : contains
pipeline__Pipeline --> renderer : contains
pipeline__PipelineBuilder --> parser : contains
pipeline__PipelineBuilder --> enricher : contains
pipeline__PipelineBuilder --> filter : contains
pipeline__PipelineBuilder --> renderer : contains
cli --> model : contains
renderer --> model : contains
filter --> cli : contains
filter --> model : contains
parser --> model : contains
parser --> File : contains
parser ..|> Visit
project --> model : contains

@enduml

